### ISSUE TITLE
viewId is cleared upon every AD_BREAK_ events

### ISSUE THREAD

**Issue by Boubalou** [newrelic/video-agent-iOS#18]
Upon heavy usage of our video data by building different dashboards with multiple widgets, we noticed that some of our events had no viewIds during ads. 

After a bit of research, we stumbled upon this line in the library: https://github.com/newrelic/video-agent-iOS/blob/master/NewRelicVideoCore/NewRelicVideoCore/Tracker/NRVideoTracker.m#L148

The viewId is actually cleared on any AD_BREAK_* event, which kind of skew our data when playing around for widget related to ads.

What is the reasoning behind this approach? We noticed Android also doing it, but not Web.

_Please note, I will enter the same issue in both repositories (iOS and Android)._

**Comment by asllop** [comment]
Hi @Boubalou, this is a missing feature we have to fix. As you said correctly, in video-core-js an Ad break contain a viewId, because this agent [gets it from the "parent" tracker](https://github.com/newrelic/video-core-js/blob/master/src/videotracker.js#LL182C17-L182C17) (an Ad tracker always comes along a "parent" that is the main content player tracker), but this feature is not implemented in iOS and Android trackers. I'll keep this issue open while we implement it.

**Comment by Boubalou** [comment]
It sure does!
